services:
  telegram-bot-api:
    build: 
      context: telegram-bot-api
      args:
        - BUILD_CPU_COUNT=${BUILD_CPU_COUNT}
    env_file: 
      - .env
    environment:
      - TELEGRAM_LOCAL=true
    restart: always
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

  goodsecretarybot:
    build: .
    entrypoint: ./entrypoint.sh
    environment:
      ALL_PROXY: "socks5h://warp:1080"
      HTTPS_PROXY: "socks5h://warp:1080"
      HTTP_PROXY: "socks5h://warp:1080"
    command: uv run src/manage.py runbot
    env_file: 
      - .env
    restart: always
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./data:/app/data
    depends_on:
      - telegram-bot-api

  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # add removed rule back (https://github.com/opencontainers/runc/pull/3468)
    device_cgroup_rules:
      - 'c 10:200 rwm'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
      # - WARP_ENABLE_NAT=1 # enable nat
    cap_add:
      # Docker already have them, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
      # uncomment for nat
      # - net.ipv4.ip_forward=1
      # - net.ipv6.conf.all.forwarding=1
      # - net.ipv6.conf.all.accept_ra=2
    volumes:
      - ./warp-data:/var/lib/cloudflare-warp

volumes:
  telegram-bot-api-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=500m,uid=1000"
